<?
    $this->headLink()->prependStylesheet('/yhack/css/common.css');
    $this->headScript()->appendFile('/yhack/js/jquery.tinyscrollbar.min.js');
    $this->headScript()->appendFile('/yhack/js/jquery.cookie.js');
    $this->headScript()->appendFile('/js/yHack.js');
    $this->headScript()->appendFile('http://www.youtube.com/player_api');
?>
<html>
    <head>
        <?= $this->headMeta() ?>
        <?= $this->headLink() ?>

        <?= $this->jQuery() ?>
        <?= $this->headScript() ?>

        <!--[if IE]>
            <script>alert("We haven't tested IE and it probably won't work");</script>
        <![endif]-->
    </head>
    <body>
        <div id="grass">
            <div id="grass-top"></div>
            <div id="grass-bottom"></div>
        </div>

        <div id="container">
            <div id="logo">Mood Music</div>
            <div id="sun"></div>

            <div id="searchbox">
                <input id="search" name="search" type="text" placeholder="Type your city to find music matching your weather." autocomplete="off" value="" />
                <div id="spinner"></div>
            </div>

            <div id="playlist" style="display: none;">
                <div id="songs">
                    <div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>
                    <div class="viewport">
                        <div class="overview"> 
                            <div class="song" data-video="vx2u5uUu3DE">
                                <img src="http://userserve-ak.last.fm/serve/34s/41161483.png" class="cover" />
                                <div class="title">Born This Way</div>
                                <div class="artist">Lady Gaga</div>
                            </div>
                            <div class="song" data-video="bESGLojNYSo">
                                <img src="http://userserve-ak.last.fm/serve/34s/34568217.jpg" class="cover" />
                                <div class="title">Born This Way</div>
                                <div class="artist">Lady Gaga</div>
                            </div>
                            <div class="song" data-video="qrO4YZeyl0I">
                                <img src="http://userserve-ak.last.fm/serve/34s/34568217.jpg" class="cover" />
                                <div class="title">Born This Way</div>
                                <div class="artist">Lady Gaga</div>
                            </div>
                            <div class="song" data-video="vx2u5uUu3DE">
                                <img src="http://userserve-ak.last.fm/serve/34s/41161483.png" class="cover" />
                                <div class="title">Born This Way</div>
                                <div class="artist">Lady Gaga</div>
                            </div>
                            <div class="song" data-video="bESGLojNYSo">
                                <img src="http://userserve-ak.last.fm/serve/34s/34568217.jpg" class="cover" />
                                <div class="title">Born This Way</div>
                                <div class="artist">Lady Gaga</div>
                            </div>
                            <div class="song" data-video="qrO4YZeyl0I">
                                <img src="http://userserve-ak.last.fm/serve/34s/34568217.jpg" class="cover" />
                                <div class="title">Born This Way</div>
                                <div class="artist">Lady Gaga</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="youtube" style="display: none;">
            </div>

            <div id="tree"></div>

            <footer>
                Built for the <a href="http://openhackeu2011.eventbrite.com/">Yahoo! Open Hack Europe 2011</a> by
                    <a href="http://blog.motane.lu/">Tudor</a>,
                    <a href="http://twitter.com/adolfoabegg">Adolfo</a> and
                    <a href="http://www.helpdeskhq.com/">Alex</a>.<br/>
                Uses <a href="http://developer.yahoo.com/yql/">YQL</a>,
                    <a href="http://developer.yahoo.com/weather/">Yahoo Weather</a>,
                    <a href="http://www.last.fm/api">Last.fm</a>,
                    <a href="http://www.jquery.com/">jQuery</a>,
                    <a href="http://compass-style.org/">Sass</a>,
                    <a href="http://code.google.com/apis/youtube/">YouTube</a>,
                    <a href="http://www.geonames.org/export/ws-overview.html">Geonames.org</a>
                    and Red Bull.
                    Built with <a href="http://framework.zend.com/">Zend Framework</a>.
                    Available on <a href="https://github.com/adolfoabegg/hackyMusic">GitHub</a>.
            </footer>
        </div>
        
        <!-- SCROLLBAR -->
    
        <script>
            var scrollport = $('#songs');
            scrollport.tinyscrollbar();
        </script>

        <!-- CITY -->

        <script>
            $('#search').autocomplete({
                source: function(request, response) {
                    $.ajax({
                        url: "http://ws.geonames.org/searchJSON",
                        dataType: "jsonp",
                        data: {
                            featureClass: "P",
                            style: "full",
                            maxRows: 5,
                            name_startsWith: request.term
                        },
                        success: function( data ) {
                            response($.map(data.geonames, function(item) {
                                return {
                                    label: yHack.highlightAutocompleteItem(item.name + ", " + item.countryName, request.term),
                                    value: item.name + ", " + item.countryName
                                }
                            }));
                        }
                    });
                },
                minLength: 2,
                search: function() {
                    yHack.showSpinner();
                },
                open: function() {
                    yHack.hideSpinner();
                },
                select: function(event, ui) {
                    $.cookie('customLocation', ui.item.value)
                    yHack.search();
                }
            }).data( "autocomplete" )._renderItem = function(ul, item) {
                  // only change here was to replace .text() with .html()
                  return $( "<li></li>" )
                        .data( "item.autocomplete", item )
                        .append( $( "<a></a>" ).html(item.label) )
                        .appendTo( ul );
            };
        </script>

        <!-- YOUTUBE -->

        <script>
            var player;

            function onYouTubePlayerAPIReady() {
                player = new YT.Player('youtube', {
                height: '27',
                width: '300',
                videoId: 'qrO4YZeyl0I',
                playerVars: {
                    fs: 0,
                    iv_load_policy: 3
                },
                events: {
                    'onReady': onPlayerReady,
                    'onStateChange': onPlayerStateChange
                }
                });
            }

            function onPlayerReady(event) {
                // event.target.playVideo();
            }

            function onPlayerStateChange(event) {
                if (event.data == YT.PlayerState.ENDED) {
                    yHack.play($('.song.playing').next());
                }
            }
        </script>

        <!-- TRACKER -->
        <script src="//static.getclicky.com/js" type="text/javascript"></script>
        <script type="text/javascript">try{ clicky.init(66425014); }catch(e){}</script>
        <noscript><p><img alt="Clicky" width="1" height="1" src="//in.getclicky.com/66425014ns.gif" /></p></noscript>
    </body>
</html>

