<?
    $this->headLink()->prependStylesheet('/yhack/css/common.css');
?>
<html>
    <head>
        <?= $this->headMeta() ?>
        <?= $this->headLink() ?>

        <?= $this->headScript() ?>

        
    </head>
    <body>
        <div id="container">
            <div id="logo">Mood Music</div>
            <div id="sun"></div>

            <div id="searchbox">
                <input type="" name="searchbox" placeholder="Type your city to find music matching your weather" value="" />
            </div>

            <div id="playlist">
                <div class="song">
                    <img src="" alt="" class="cover" />
                    <div class="title"></div>
                    <div class="artist"></div>
                    <div class="youtube"></div>
                </div>
                <div class="song">
                    <img src="" alt="" class="cover" />
                    <div class="title"></div>
                    <div class="artist"></div>
                    <div class="youtube"></div>
                </div>
                <div class="song">
                    <img src="" alt="" class="cover" />
                    <div class="title"></div>
                    <div class="artist"></div>
                    <div class="youtube"></div>
                </div>
                <div class="song">
                    <img src="" alt="" class="cover" />
                    <div class="title"></div>
                    <div class="artist"></div>
                    <div class="youtube"></div>
                </div>
            </div>

            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>
    </body>
</html>

